---
- hosts: all
  sudo: yes
  tasks:
    - apt: pkg=nginx state=installed
    - apt: pkg=mysql-server state=installed
    - apt: pkg=mysql-common state=installed
    - apt: pkg=mysql-client state=instaled
    - apt: pkg=supervisor state=installed
    - apt: pkg=redis-server state=installed

