---
- hosts: all
  sudo: yes
  tasks:
    - apt: pkg=git state=installed
    - apt: pkg=mercurial state=installed
    - apt: pkg=bzr state=installed
    - command: "curl -L -O  http://golang.org/dl/go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - command: "tar -C /usr/local -xzf go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - shell: cp /home/isucon/isucon4/qualifier/ami/files/golang.sh /etc/profile.d/golang.sh
    - command: "/home/isucon/env.sh gem install --no-rdoc --no-ri gondler -v 0.2.0"
      args:
        creates: /usr/local/bin/gondler
    - command: /home/isucon/env.sh ./build.sh
      args:
        chdir: /home/isucon/webapp/go
    - command: chown -R isucon:isucon /home/isucon/gocode
