---
- hosts: all
  sudo: yes
  tasks:
    - apt: pkg=git state=installed
    - apt: pkg=mercurial state=installed
    - apt: pkg=bzr state=installed
    - command: "curl -L -O  http://golang.org/dl/go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - command: "tar -C /usr/local -xzf go1.3.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
