---
- hosts: all
  sudo: yes
  tasks:
    - name: install ruby-build
      shell: |
          if ! which ruby-build; then
            git clone https://github.com/sstephenson/ruby-build.git /usr/local/ruby-build
            cd /usr/local/ruby-build && ./install.sh
          fi
    - name: install ruby for isucon user
      shell: "{{ item }}"
      with_items:
          - test -e /home/isucon/.local || mkdir -p /home/isucon/.local
          - /home/isucon/.local/ruby/bin/ruby  --version | grep "ruby 2.1.3" || /usr/local/bin/ruby-build 2.1.3 /home/isucon/.local/ruby
          - chown -R isucon /home/isucon/.local
    - name: setup for isucon4 ruby app
      shell: "{{ item }}"
      with_items:
          - test -e /home/isucon/isucon4 || git clone https://github.com/isucon/isucon4 /home/isucon/isucon4
          - cp /home/isucon/isucon4/qualifier/ami/files/golang.sh /etc/profile.d/golang.sh
          - cp -r /home/isucon/isucon4/qualifier/* /home/isucon/
          - cp /home/isucon/ami/files/env.sh /home/isucon/
          - cp /home/isucon/ami/files/nginx.conf /etc/nginx/
          - cp /home/isucon/ami/files/my.cnf /etc/
          - chmod 755 /home/isucon/env.sh
          - /home/isucon/env.sh gem install --no-document foreman bundler
          - cd /home/isucon/webapp/ruby && /home/isucon/env.sh bundle install
    - name: setup isucon4 benchmarker
      shell: "{{ item }}"
      with_items:
          - /home/isucon/env.sh gem install --no-document gondler -v 0.2.0

          - cd /home/isucon/benchmarker && /home/isucon/env.sh make debug GIT_COMMIT=1402de0
          - cp -r /home/isucon/benchmarker /tmp/
          - cp -r /tmp/benchmarker/benchmarker /home/isucon/

          - head -n 26 /home/isucon/ami/files/supervisord.conf > /etc/supervisor/supervisord.conf
          - sed -i -e 's/wheel/root/' /etc/supervisor/supervisord.conf
    - command: "/home/isucon/env.sh gem install --no-rdoc --no-ri gondler -v 0.2.0"
      args:
        creates: /usr/local/bin/gondler
    - command: /home/isucon/env.sh ./build.sh
      args:
        chdir: /home/isucon/webapp/go
    - command: chown -R isucon:isucon /home/isucon/gocode
  pre_tasks:
    - apt: pkg=golang state=installed
    - apt: pkg=mysql-server state=installed
    - apt: pkg=nginx state=installed
    - apt: pkg=supervisor state=installed
    - apt: pkg=irqbalance state=installed
  post_tasks:
    - command: ./init.sh
      sudo_user: isucon
      args:
        chdir: /home/isucon
    - mysql_user: name=isucon password=isucon priv=*.*:ALL state=present
  handlers:
    - name: restart mysql-server
      action: service name=mysql-server state=restarted
    - name: reload nginx
      action: service name=nginx state=restarted
    - name: reload supervisor
      action: service name=supervisor state=restarted
    - name: reload irqbalance
      action: service name=irqbalance state-restarted
