---
- hosts: all
  sudo: yes
  tasks:
    - name: install default packeges
      apt: pkg={{ item }} state=installed
      with_items:
        - aptitude
        - vim
        - supervisor
        - git
        - zsh
        - htop
        - tmux
