---
- hosts: all
  sudo: yes
  tasks:
    - name: install default packeges
      apt: pkg={{ item }} state=installed
      with_items:
        - aptitude
        - pkg-config
        - build-essential
        - libxml2-dev
        - libmysqld-dev
        - libssl-dev
        - libreadline-dev
        - autoconf
        - bison
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm3
        - libgdbm-dev
        - curl
        - vim
        - supervisor
        - git
        - zsh
        - htop
        - tmux

